### ISSUE TITLE
Question, not an issue.

### ISSUE THREAD

**Issue by mykle1** [rickycodes/moonmoji#19]
I was hoping your moonmoji was going to give me the colored emoji pictures that are displayed on NPM. I'm fairly new to this sort of thing so it's quite possible that I am missing something or that I misunderstood. Would you kindly just verify for me whether or not there are colored emoji icons included or just the black and white ones that I seem to be getting. Many thanks. :-)

**Comment by rickycodes** [comment]
they should be colored:

<img width="97" alt="image" src="https://user-images.githubusercontent.com/675259/37312995-a866b49a-2623-11e8-92ab-22b42b3b1212.png">
