### ISSUE TITLE
I do not see Moonmoji in the terminal prompt

### ISSUE THREAD

**Issue by GittyMejorado** [rickycodes/moonmoji#31]
Good day.
I Installed the Technopagan theme of the OMF shell, which requires moonmoji, I installed all the dependencies needed by moonmoji and I installed moonmoji, but only one box appears at the prompt.
What am I doing wrong? How can I correct it?
Thank you for the attention

[https://imgur.com/IJ1W7HU](url)

**Comment by rickycodes** [comment]
@GittyMejorado It's possible your terminal emulator is using a typeface that doesn't support the unicode characters? For example running `moonmoji` using something like PuTTY on windows displays as ■, however when I copy and paste that square here it looks like this 🌔 

I would suggest changing the settings/typeface and seeing if that fixes things
